"""feat(db):add key id unique constraints

Revision ID: 584691fdcffa
Revises: e9c43722d1df
Create Date: 2025-07-08 12:57:48.926436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584691fdcffa'
down_revision = 'e9c43722d1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.alter_column('key_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.create_unique_constraint(None, ['key_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('key_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
