"""fix(db):increase title string length due to error

Revision ID: e9c43722d1df
Revises: 341a83dfdc56
Create Date: 2025-07-07 18:17:19.273903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c43722d1df'
down_revision = '341a83dfdc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
