"""fix(db):increase field length for col title url

Revision ID: f988e3c4630c
Revises: 584691fdcffa
Create Date: 2025-07-10 16:24:24.471504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f988e3c4630c'
down_revision = '584691fdcffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.alter_column('title_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kafka_wiki_posts', schema=None) as batch_op:
        batch_op.alter_column('title_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
